#cloud-config
ssh_import_id: ["gh:dlotterman"]

password: password
chpasswd:
    expire: false
ssh_pwauth: true

runcmd:
    - [ufw, allow, from, 192.168.122.0/24, to, any, port, 22] # default libvirt rootful network
    - [ufw, allow, from, 10.0.2.2, to, any, port, 22] # default libvirt rootless network
    - [ufw, allow, from, 192.168.122.0/24, to, any, port, 9090] # default libvirt rootful network
    - [ufw, allow, from, 10.0.2.2, to, any, port, 9090] # default libvirt rootless network
    - [ufw, allow, from, 192.168.122.0/24, to, any, port, 3000] # default libvirt rootful network
    - [ufw, allow, from, 10.0.2.2, to, any, port, 3000] # default libvirt rootless network

write_files:
    - path: /opt/nouci/etc/nouci_hosts.yaml
      owner: root:root
      append: false
      content: |
        icmp_5m:
          - localhost
          - 1.1.1.1
