runcmd:
    - [systemctl, daemon-reload]
    - [systemctl, enable, --now, nouci_prometheus.service]
    - [ufw, allow, from, 172.17.0.1/16, to, any, port, 9090]

write_files:
    - path: /etc/systemd/system/nouci_prometheus.service
      owner: root:root
      append: false
      content: |
          [Unit]
          Description=nouci_prometheus
          Requires=nouci_disk_enc_first_boot.service docker.service network-online.target
          After=nouci_node_exporter.service nouci_blackbox_exporter.service
          ConditionPathIsEncrypted=/mnt/opt/nouci_data/ready
          [Service]
          Type=simple
          Restart=no
          ExecStartPre=-/usr/bin/docker stop nouci_prometheus
          ExecStartPre=-/usr/bin/docker rm nouci_prometheus
          ExecStartPre=docker image pull prom/prometheus
          ExecStartPre=mkdir -p /mnt/opt/nouci_data/prometheus/data
          ExecStart=docker run --name nouci_prometheus \
          -p 9090:9090  \
          --user %u \
          -v /mnt/opt/nouci_data/prometheus/data:/prometheus \
          -v /opt/nouci/prometheus/config/nouci_prometheus.yaml:/etc/prometheus/prometheus.yml \
          -v /opt/nouci/prometheus/config/scrape_d:/etc/prometheus/scrape_d \
          prom/prometheus
          ExecStop=/usr/bin/docker stop -t 30 nouci_prometheus
          TimeoutStartSec=120
          TimeoutStopSec=45
          [Install]
          WantedBy=multi-user.target

    - path: /opt/nouci/prometheus/config/nouci_prometheus.yaml
      owner: root:root
      append: false
      content: |
          global:
            scrape_interval: 15s
            evaluation_interval: 15s
          alerting:
            alertmanagers:
              - static_configs:
                  - targets:
          rule_files:
          scrape_config_files:
              - "/etc/prometheus/scrape_d/*yaml"
          scrape_configs:
            - job_name: "nouci_prometheus"
              static_configs:
                - targets: ["172.16.16.249:9090"]
                  labels:
                    app: "nouci_prometheus"
            - job_name: "nouci_node_exporter"
              static_configs:
                - targets: ['172.16.16.249:9100']
                  labels:
                    app: "nouci_node_exporter"
