runcmd:
    - [systemctl, daemon-reload]
    - [systemctl, enable, --now, nouci_grafana.service]
    - [ufw, allow, from, 172.17.0.1/16, to, any, port, 3000]

write_files:
    - path: /etc/systemd/system/nouci_grafana.service
      owner: root:root
      append: false
      content: |
          [Unit]
          Description=nouci_grafana
          Requires=docker.service network-online.target
          After=nouci_prometheus.service
          ConditionPathIsEncrypted=/mnt/opt/nouci_data/ready
          [Service]
          Type=simple
          Restart=no
          ExecStartPre=-/usr/bin/docker stop nouci_grafana
          ExecStartPre=-/usr/bin/docker rm nouci_grafana
          ExecStartPre=docker image pull grafana/grafana
          ExecStartPre=-mkdir -p /mnt/nouci/data
          ExecStart=docker run --name nouci_grafana \
          -p 3000:3000  \
          --user %u \
          -v /etc/timezone:/etc/timezone:ro \
          -v /etc/localtime:/etc/localtime:ro \
          -v /mnt/nouci/data:/var/lib/grafana \
          -v /opt/nouci/grafana/config/nouci_prometheus.yaml:/etc/grafana/provisioning/datasources/nouci_prometheus.yaml \
          -v /opt/nouci/nouci/grafana/assets/1860_rev43.json:/var/lib/grafana/dashboards/1860_rev43.json \
          -v /opt/nouci/nouci/grafana/assets/nouci_quick_dash.json:/var/lib/grafana/dashboards/nouci_quick_dash.json \
          -v /opt/nouci/grafana/config/dashboard-provider.yaml:/etc/grafana/provisioning/dashboards/dashboard-provider.yaml \
          grafana/grafana
          ExecStop=/usr/bin/docker stop -t 30 nouci_grafana
          TimeoutStartSec=120
          TimeoutStopSec=45
          [Install]
          WantedBy=multi-user.target

    - path: /opt/nouci/grafana/config/nouci_prometheus.yaml
      owner: root:root
      append: false
      content: |
          apiVersion: 1
          datasources:
            - name: nouci_prometheus
              type: prometheus
              access: proxy
              # Access mode - proxy (server in the UI) or direct (browser in the UI).
              url: http://172.16.16.249:9090
              isDefault: true
              editable: true

    - path: /opt/nouci/grafana/config/dashboard-provider.yaml
      owner: root:root
      append: false
      content: |
          apiVersion: 1

          providers:
            - name: 'default'
              orgId: 1
              folder: 'nouci_builtin'
              type: file
              disableDeletion: false
              updateIntervalSeconds: 30
              allowUiUpdates: true
              editable: true
              options:
                path: /var/lib/grafana/dashboards
